"""add projects decisions options tags audit_log

Revision ID: 9c2555961390
Revises: 6980ac1ad714
Create Date: 2026-03-04 21:18:06.872167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2555961390'
down_revision = '6980ac1ad714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tags_name', ['name'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('final_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(superseded_by IS NULL) OR (status = 'Superseded')", name='supersede_status_sync'),
    sa.CheckConstraint('superseded_by != id', name='no_self_supersede'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('idx_decisions_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_decisions_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_decisions_status', ['status'], unique=False)
        batch_op.create_index('idx_decisions_superseded_by', ['superseded_by'], unique=True, postgresql_where=sa.text('superseded_by IS NOT NULL'))

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_log_actor_id', ['actor_id'], unique=False)
        batch_op.create_index('idx_audit_log_decision_id', ['decision_id'], unique=False)

    op.create_table('decision_tags',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', 'tag_id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pros', sa.Text(), nullable=True),
    sa.Column('cons', sa.Text(), nullable=True),
    sa.Column('is_chosen', sa.Boolean(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_index('idx_one_chosen_option_per_decision', ['decision_id'], unique=True, postgresql_where=sa.text('is_chosen = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index('idx_one_chosen_option_per_decision', postgresql_where=sa.text('is_chosen = true'))

    op.drop_table('options')
    op.drop_table('decision_tags')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_log_decision_id')
        batch_op.drop_index('idx_audit_log_actor_id')

    op.drop_table('audit_log')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('idx_decisions_superseded_by', postgresql_where=sa.text('superseded_by IS NOT NULL'))
        batch_op.drop_index('idx_decisions_status')
        batch_op.drop_index('idx_decisions_project_id')
        batch_op.drop_index('idx_decisions_created_by')

    op.drop_table('decisions')
    op.drop_table('projects')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tags_name')

    op.drop_table('tags')
    # ### end Alembic commands ###
